name: generate snake animation GIF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create images folder
        run: mkdir -p images

      - name: generate snake.gif
        uses: Platane/snk@v3
        with:
          github_user_name: qwo877
          outputs: images/snake.gif

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images/snake.gif
          git commit -m "generated snake GIF animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
