name: generate snake animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create images folder
        run: mkdir -p images

      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: qq123
          outputs: images/snake.svg

      - name: push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "generated snake animation"
          add: "images/snake.svg"
